### ISSUE TITLE
VNC not connecting

### ISSUE THREAD

**Issue by AlexP11223** [deviantintegral/drupal-playwright#1] opened 2023-04-28 13:28 UTC
Hi, I tried to use this setup, but VNC does not seem to work for me. Linux, latest DDEV (1.21.6).

https://drupal-playwright.ddev.site:7900/ is stuck `Connecting` without any errors in console, and a desktop client also does not show anything (and does not ask the password, but no connection error like when the server is not running).

`ddev logs` seems fine

```
...

Created a new certificate valid for the following names 📜 - "drupal-playwright.ddev.site"
 - "localhost"
 - "127.0.0.1"
 - "127.0.0.1"
 - "web"
 - "ddev-drupal-playwright-web"
 - "ddev-drupal-playwright-web.ddev"

...

+ echo 'Server started'
+ unset PHP_IDE_CONFIG
Server started
+ '[' -d /mnt/ddev_config/web-entrypoint.d ']'
++ find /mnt/ddev_config/web-entrypoint.d -type f -regex '.*\.\(sh\)'
+ [[ -n '' ]]
+ exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord-nginx-fpm.conf
2023-04-28 12:45:47,763 INFO Included extra file "/etc/supervisor/php-fpm.conf" during parsing
2023-04-28 12:45:47,764 INFO Included extra file "/etc/supervisor/conf.d/mailhog.conf" during parsing
2023-04-28 12:45:47,764 INFO Included extra file "/etc/supervisor/conf.d/novnc.conf" during parsing
2023-04-28 12:45:47,764 INFO Included extra file "/etc/supervisor/conf.d/supervisor.conf" during parsing
2023-04-28 12:45:47,764 INFO Included extra file "/etc/supervisor/conf.d/vnc.conf" during parsing
2023-04-28 12:45:47,764 INFO Included extra file "/etc/supervisor/conf.d/webextradaemons.conf" during parsing
2023-04-28 12:45:47,764 INFO Included extra file "/etc/supervisor/conf.d/xvfb.conf" during parsing
2023-04-28 12:45:47,767 INFO RPC interface 'supervisor' initialized
2023-04-28 12:45:47,767 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-04-28 12:45:47,767 INFO supervisord started with pid 1
2023-04-28 12:45:48,768 INFO spawned: 'child_exit_monitor' with pid 1882
2023-04-28 12:45:48,769 INFO spawned: 'php-fpm' with pid 1883
2023-04-28 12:45:48,770 INFO spawned: 'nginx' with pid 1884
2023-04-28 12:45:48,771 INFO spawned: 'mailhog' with pid 1885
[28-Apr-2023 12:45:49] NOTICE: fpm is running, pid 1883
[28-Apr-2023 12:45:49] NOTICE: ready to handle connections
[28-Apr-2023 12:45:49] NOTICE: systemd monitor interval set to 10000ms
2023-04-28 12:45:50,039 INFO success: child_exit_monitor entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-04-28 12:45:50,039 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-04-28 12:45:50,039 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-04-28 12:45:50,039 INFO success: mailhog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-04-28 12:45:50,359 INFO spawned: 'xvfb' with pid 1950
2023-04-28 12:45:50,360 INFO spawned: 'vnc' with pid 1951
2023-04-28 12:45:50,361 INFO spawned: 'novnc' with pid 1952
+ START_XVFB=true
+ DISPLAY=:99.0
+ VNC_PORT=5900
+ '[' true = true ']'
+ VNC_NO_PASSWORD=
+ '[' '!' -z ']'
+ X11VNC_OPTS=-usepw
+ VNC_VIEW_ONLY=
+ '[' '!' -z ']'
++ seq 1 10
+ START_XVFB=true
+ SCREEN_WIDTH=1360
+ SCREEN_HEIGHT=1020
+ SCREEN_DEPTH=24
+ SCREEN_DPI=96
+ DISPLAY=:99.0
+ DISPLAY_NUM=99
+ SCREEN_WIDTH=1360
+ for i in $(seq 1 10)
+ sleep 1
+ SCREEN_HEIGHT=1020
+ SCREEN_DEPTH=24
+ SCREEN_DPI=96
+ '[' true = true ']'
+ export GEOMETRY=1360x1020x24
+ GEOMETRY=1360x1020x24
+ rm -f '/tmp/.X*lock'
+ /usr/bin/xvfb-run --server-num=99 --listen-tcp '--server-args=-screen 0 1360x1020x24 -fbdir /var/tmp -dpi 96 -listen tcp -noreset -ac +extension RANDR' /usr/bin/fluxbox -display :99.0
Warning: could not find self.pem
Using local websockify at /opt/bin/noVNC/utils/websockify/run
Starting webserver and WebSockets proxy on port 7900
/opt/bin/noVNC/utils/websockify/websockify/websocket.py:31: UserWarning: no 'numpy' module, HyBi protocol will be slower
  warnings.warn("no 'numpy' module, HyBi protocol will be slower")
Warning: Failed to open file(/usr/share/fluxbox/nls/C.UTF-8/fluxbox.cat)
for translation, using default messages.
WebSocket server settings:
  - Listen on :7900
  - Web server. Web root: /opt/bin/noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :7900 to localhost:5900
Failed to read: session.ignoreBorder
Setting default value
......
Failed to read: session.screen0.iconbar.usePixmap
Setting default value
+ xdpyinfo -display :99.0
2023-04-28 12:45:51,417 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-04-28 12:45:51,417 INFO success: vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-04-28 12:45:51,417 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
+ '[' 0 -eq 0 ']'
+ break
+ x11vnc -usepw -forever -shared -rfbport 5900 -rfbportv6 5900 -display :99.0
28/04/2023 12:45:51 passing arg to libvncserver: -rfbport
28/04/2023 12:45:51 passing arg to libvncserver: 5900
28/04/2023 12:45:51 passing arg to libvncserver: -rfbportv6
28/04/2023 12:45:51 passing arg to libvncserver: 5900
28/04/2023 12:45:51 -usepw: found /home/alex/.vnc/passwd
28/04/2023 12:45:51 x11vnc version: 0.9.16 lastmod: 2019-01-05  pid: 2219
28/04/2023 12:45:51 Using X display :99.0
28/04/2023 12:45:51 rootwin: 0x50e reswin: 0x400001 dpy: 0xa8bea430
28/04/2023 12:45:51 
28/04/2023 12:45:51 ------------------ USEFUL INFORMATION ------------------
28/04/2023 12:45:51 X DAMAGE available on display, using it for polling hints.
28/04/2023 12:45:51   To disable this behavior use: '-noxdamage'
28/04/2023 12:45:51 
28/04/2023 12:45:51   Most compositing window managers like 'compiz' or 'beryl'
28/04/2023 12:45:51   cause X DAMAGE to fail, and so you may not see any screen
28/04/2023 12:45:51   updates via VNC.  Either disable 'compiz' (recommended) or
28/04/2023 12:45:51   supply the x11vnc '-noxdamage' command line option.
28/04/2023 12:45:51 
28/04/2023 12:45:51 Wireframing: -wireframe mode is in effect for window moves.
28/04/2023 12:45:51   If this yields undesired behavior (poor response, painting
28/04/2023 12:45:51   errors, etc) it may be disabled:
28/04/2023 12:45:51    - use '-nowf' to disable wireframing completely.
28/04/2023 12:45:51    - use '-nowcr' to disable the Copy Rectangle after the
28/04/2023 12:45:51      moved window is released in the new position.
28/04/2023 12:45:51   Also see the -help entry for tuning parameters.
28/04/2023 12:45:51   You can press 3 Alt_L's (Left "Alt" key) in a row to 
28/04/2023 12:45:51   repaint the screen, also see the -fixscreen option for
28/04/2023 12:45:51   periodic repaints.
28/04/2023 12:45:51 
28/04/2023 12:45:51 XFIXES available on display, resetting cursor mode
28/04/2023 12:45:51   to: '-cursor most'.
28/04/2023 12:45:51   to disable this behavior use: '-cursor arrow'
28/04/2023 12:45:51   or '-noxfixes'.
28/04/2023 12:45:51 using XFIXES for cursor drawing.
28/04/2023 12:45:51 GrabServer control via XTEST.
28/04/2023 12:45:51 
28/04/2023 12:45:51 Scroll Detection: -scrollcopyrect mode is in effect to
28/04/2023 12:45:51   use RECORD extension to try to detect scrolling windows
28/04/2023 12:45:51   (induced by either user keystroke or mouse input).
28/04/2023 12:45:51   If this yields undesired behavior (poor response, painting
28/04/2023 12:45:51   errors, etc) it may be disabled via: '-noscr'
28/04/2023 12:45:51   Also see the -help entry for tuning parameters.
28/04/2023 12:45:51   You can press 3 Alt_L's (Left "Alt" key) in a row to 
28/04/2023 12:45:51   repaint the screen, also see the -fixscreen option for
28/04/2023 12:45:51   periodic repaints.
28/04/2023 12:45:51 
28/04/2023 12:45:51 XKEYBOARD: number of keysyms per keycode 7 is greater
28/04/2023 12:45:51   than 4 and 51 keysyms are mapped above 4.
28/04/2023 12:45:51   Automatically switching to -xkb mode.
28/04/2023 12:45:51   If this makes the key mapping worse you can
28/04/2023 12:45:51   disable it with the "-noxkb" option.
28/04/2023 12:45:51   Also, remember "-remap DEAD" for accenting characters.
28/04/2023 12:45:51 
28/04/2023 12:45:51 X FBPM extension not supported.
Xlib:  extension "DPMS" missing on display ":99.0".
28/04/2023 12:45:51 X display is not capable of DPMS.
28/04/2023 12:45:51 --------------------------------------------------------
28/04/2023 12:45:51 
28/04/2023 12:45:51 Default visual ID: 0x21
28/04/2023 12:45:51 Read initial data from X display into framebuffer.
28/04/2023 12:45:51 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5440
28/04/2023 12:45:51 
28/04/2023 12:45:51 X display :99.0 is 32bpp depth=24 true color
28/04/2023 12:45:51 
28/04/2023 12:45:51 Listening for VNC connections on TCP port 5900
28/04/2023 12:45:51 Listening for VNC connections on TCP6 port 5900
28/04/2023 12:45:51 listen6: bind: Address already in use
28/04/2023 12:45:51 Not listening on IPv6 interface.
28/04/2023 12:45:51 
28/04/2023 12:45:51 Xinerama is present and active (e.g. multi-head).
28/04/2023 12:45:51 Xinerama: number of sub-screens: 1
28/04/2023 12:45:51 Xinerama: no blackouts needed (only one sub-screen)
28/04/2023 12:45:51 
28/04/2023 12:45:51 fb read rate: 1749 MB/sec
28/04/2023 12:45:51 fast read: reset -wait  ms to: 10
28/04/2023 12:45:51 fast read: reset -defer ms to: 10
28/04/2023 12:45:51 The X server says there are 10 mouse buttons.
28/04/2023 12:45:51 screen setup finished.
28/04/2023 12:45:51 

The VNC desktop is:      drupal-playwright-web:0
PORT=5900

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching



Navigate to this URL:

    http://drupal-playwright-web:7900/vnc.html?host=drupal-playwright-web&port=7900

Press Ctrl-C to exit


.......

172.20.0.6 - - [28/Apr/2023 12:47:31] 172.20.0.6: Plain non-SSL (ws://) WebSocket connection
172.20.0.6 - - [28/Apr/2023 12:47:31] 172.20.0.6: Path: '/websockify'
172.20.0.6 - - [28/Apr/2023 12:47:31] connecting to: localhost:5900
Failed to read: session.screen0.titlebar.left
Setting default value
Failed to read: session.screen0.titlebar.right
Setting default value
2023-04-28 12:47:47,619 INFO reaped unknown pid 13565 (exit status 0)
.....
2023-04-28 12:47:49,913 INFO reaped unknown pid 17477 (exit status 0)
handler exception: [Errno 32] Broken pipe
172.20.0.6 - - [28/Apr/2023 12:48:11] 172.20.0.6: Plain non-SSL (ws://) WebSocket connection
172.20.0.6 - - [28/Apr/2023 12:48:11] 172.20.0.6: Path: '/websockify'
172.20.0.6 - - [28/Apr/2023 12:48:11] connecting to: localhost:5900
```

**Comment by deviantintegral** [comment] 2023-05-01 12:30
> 2023-04-28 12:47:47,619 INFO reaped unknown pid 13565 (exit status 0)
> .....
> 2023-04-28 12:47:49,913 INFO reaped unknown pid 17477 (exit status 0)
> handler exception: [Errno 32] Broken pipe

That seems like an issue. I'll see if I can reproduce. We have this code running in a private repo which is working, so perhaps there's just something here I need to update.

I also have plans to swap this for https://github.com/kasmtech/KasmVNC which offers really good performance - I was able to watch a YouTube video (with no sound) and it was as smooth as a normal web browser.

**Comment by deviantintegral** [comment] 2023-05-01 12:37
I just walked through the README steps with a fresh install and VNC is working for me. Is it possible you're running out of memory or something? I wonder what those processes are that are exiting.

**Comment by AlexP11223** [comment] 2023-05-01 14:28
Yeah, I did the readme steps, just cloning this repo. The PC has lots of memory, not sure if ddev has any limit.

After restart the `reaped` messages disappeared, but still not connecting.

```
...
Navigate to this URL:

    http://drupal-playwright-web:7900/vnc.html?host=drupal-playwright-web&port=7900

Press Ctrl-C to exit


handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
handler exception: [Errno 32] Broken pipe
172.27.0.6 - - [01/May/2023 14:24:51] 172.27.0.6: Plain non-SSL (ws://) WebSocket connection
172.27.0.6 - - [01/May/2023 14:24:51] 172.27.0.6: Path: '/websockify'
172.27.0.6 - - [01/May/2023 14:24:51] connecting to: localhost:5900
```

**Comment by deviantintegral** [comment] 2023-05-01 14:45
What's your host environment? You said "PC", so WSL2 or linux?

It certainly seems like a process is crashing given the broken pipe. Are there any segfaults registered on the Docker host if you run `sudo dmesg`? You'd get there with something like `wsl` or `colima ssh` or whatever you're using.

**Comment by AlexP11223** [comment] 2023-05-01 14:50
Arch Linux (EndeavourOS). No errors in `dmesg` :(

**Comment by rfay** [comment] 2023-05-01 14:53
If you're on Linux, then IIRC Docker can use all the memory you have available. 

Since Arch is always "out there" it would probably help if you could try it in a different environment. Working with Arch is always like using the latest alpha of everything.

**Comment by deviantintegral** [comment] 2023-05-03 01:23
Now that we've had this running on a project for a while, I'm working on making this a normal ddev addon, with tests!

https://github.com/deviantintegral/ddev-playwright/pull/1

I'm still going to convert the addon to kasmvnc. If you figure out a reproduction case _and_ it's not novnc specific, we can add a test in the other repo.

**Comment by deviantintegral** [comment] 2023-05-03 01:25
@rfay if you have any thoughts on https://github.com/deviantintegral/ddev-playwright/pull/1/files#diff-a2bb1b04da80b87de17520a6aac3664b1cafdec2b6431697f15968522708a47cR8-R26 with parallel tests I'd appreciate it. Even with the lock, this saves a minute or two on my local for running tests. I wonder if ddev should have internal locks around certain ops, or if those locks exist but are broken somehow.

**Comment by rfay** [comment] 2023-05-03 03:52
Looks like some good stuff; I haven't tried parallel tests in any context (except separate VMs) because of port and namespace issues. With the general assumption of keeping the same ports, you really can't have two DDEV tests going at the same time very well, and if they're using the same namespace/project name then one will destroy the other when coming up or going down.

**Comment by deviantintegral** [comment] 2023-05-06 01:18
I'm going to close this as I've finished a first version of a proper ddev addon at https://github.com/deviantintegral/ddev-playwright. Note the drupal side is still useful, but my next task is to split that out into a reusable library too. Then I think I can archive this repo.

One more thing @AlexP11223 : In writing tests I discovered that KasmVNC would only work with traefik as the ddev router. I wonder if you are facing something similar? However, I'm pretty sure others on my team aren't using traefik and can use novnc... but perhaps they are running playwright on the host.

https://github.com/deviantintegral/ddev-playwright/commit/cba3b7a976ef038b65efef8622002d9e41d072c4

If you run into the same issue, feel free to open one in the addon repo. Thanks!

**Closed as completed by deviantintegral** 2023-05-06 01:18 UTC

**Comment by AlexP11223** [comment] 2023-05-06 08:27
Oh, looks like it actually works (the same with and without traefik), the problem is that for some reason it needs 6 minutes to proceed from `Connecting` to the password input.

```
172.27.0.6 - - [06/May/2023 08:20:09] 172.27.0.6: Plain non-SSL (ws://) WebSocket connection
172.27.0.6 - - [06/May/2023 08:20:09] 172.27.0.6: Path: '/websockify'
172.27.0.6 - - [06/May/2023 08:20:09] connecting to: localhost:5900
06/05/2023 08:26:08 Got connection from client 127.0.0.1
06/05/2023 08:26:08   0 other clients
06/05/2023 08:26:08 Normal socket connection
06/05/2023 08:26:08 Disabled X server key autorepeat.
06/05/2023 08:26:08   to force back on run: 'xset r on' (3 times)
06/05/2023 08:26:08 incr accepted_client=2 for 127.0.0.1:53332  sock=10
06/05/2023 08:26:08 Client Protocol Version 3.8
06/05/2023 08:26:08 Protocol version sent 3.8, using 3.8
06/05/2023 08:26:08 rfbProcessClientSecurityType: executing handler for type 2
06/05/2023 08:26:09 created   xdamage object: 0x400031
06/05/2023 08:26:17 Pixel format for client 127.0.0.1:
06/05/2023 08:26:17   32 bpp, depth 24, little endian
06/05/2023 08:26:17   true colour: max r 255 g 255 b 255, shift r 0 g 8 b 16
06/05/2023 08:26:17 rfbProcessClientNormalMessage: ignoring unsupported encoding type tightPng
06/05/2023 08:26:17 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x00000015)
06/05/2023 08:26:17 Using image quality level 6 for client 127.0.0.1
06/05/2023 08:26:17 Using JPEG subsampling 0, Q79 for client 127.0.0.1
06/05/2023 08:26:17 Using compression level 2 for client 127.0.0.1
06/05/2023 08:26:17 Enabling NewFBSize protocol extension for client 127.0.0.1
06/05/2023 08:26:17 Enabling LastRect protocol extension for client 127.0.0.1
06/05/2023 08:26:17 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEFE)
06/05/2023 08:26:17 Enabling ExtDesktopSize protocol extension for client 127.0.0.1
06/05/2023 08:26:17 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEC8)
06/05/2023 08:26:17 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEC7)
06/05/2023 08:26:17 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECD)
06/05/2023 08:26:17 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xC0A1E5CE)
06/05/2023 08:26:17 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x574D5664)
06/05/2023 08:26:17 Enabling full-color cursor updates for client 127.0.0.1
06/05/2023 08:26:17 Using tight encoding for client 127.0.0.1
06/05/2023 08:26:17 Sending rfbEncodingExtDesktopSize for size (1360x1020) 
06/05/2023 08:26:17 client_set_net: 127.0.0.1  0.0002
06/05/2023 08:26:17 client 2 network rate 3507.9 KB/sec (98891.0 eff KB/sec)
06/05/2023 08:26:17 client 2 latency:  6.3 ms
06/05/2023 08:26:17 dt1: 0.0286, dt2: 0.0307 dt3: 0.0063 bytes: 196926
06/05/2023 08:26:17 link_rate: LR_LAN - 6 ms, 3507 KB/s
```

**Comment by AlexP11223** [comment] 2023-05-27 08:24
https://github.com/deviantintegral/ddev-playwright seems to work without this issue for me.
